[package]
name = "fusion-extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = "51.0.0"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
arrow-ops = { path = "../arrow-ops" }
arrow-array = "57.1.0"
